const DB_KEY="ttt-os-v0.2";
const STATUSES=["Lead","Estimate","Awaiting Approval","Scheduled","Awaiting Parts","Ready for Check-In","Checked In","Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts","QC","Ready for Pickup","Delivered","Closed","Declined"];
const SERVICES=["Car stereo installation","Car alarms","Radar detectors","Dash cams","Paint protection","Marine audio","Window tint","GPS trackers","Interior lighting","Exterior lighting","Truck accessories","Other"];
const STATES="AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY DC".split(" ");
const VEHICLE_CATALOG={"Acura":["Integra","TLX","RDX","MDX"],"Audi":["A3","A4","A5","A6","Q3","Q5","Q7","Q8"],"BMW":["2 Series","3 Series","4 Series","5 Series","X1","X3","X5","X7","i4","i5","iX"],"Cadillac":["CT4","CT5","XT4","XT5","XT6","Escalade","LYRIQ"],"Chevrolet":["Trax","Trailblazer","Equinox","Blazer","Traverse","Tahoe","Suburban","Colorado","Silverado 1500","Silverado HD","Corvette"],"Dodge":["Charger","Challenger","Durango","Hornet"],"Ford":["Mustang","Escape","Bronco Sport","Bronco","Explorer","Expedition","Maverick","Ranger","F-150","F-150 Lightning","Super Duty","Transit"],"GMC":["Terrain","Acadia","Yukon","Canyon","Sierra 1500","Sierra HD","Hummer EV"],"Honda":["Civic","Accord","HR-V","CR-V","Passport","Pilot","Ridgeline","Odyssey","Prologue"],"Hyundai":["Elantra","Sonata","Kona","Tucson","Santa Fe","Palisade","Santa Cruz","Ioniq 5","Ioniq 6"],"Jeep":["Compass","Grand Cherokee","Wrangler","Gladiator","Wagoneer","Grand Wagoneer"],"Kia":["K4","K5","Soul","Seltos","Sportage","Sorento","Telluride","Carnival","EV6","EV9"],"Lexus":["IS","ES","LS","UX","NX","RX","TX","GX","LX"],"Mercedes-Benz":["C-Class","E-Class","S-Class","CLA","CLE","GLA","GLB","GLC","GLE","GLS","G-Class","EQE","EQS"],"Nissan":["Versa","Sentra","Altima","Kicks","Rogue","Murano","Pathfinder","Armada","Frontier","Titan","Z","Leaf","Ariya"],"Porsche":["718","911","Panamera","Macan","Cayenne","Taycan"],"Ram":["1500","2500","3500","ProMaster"],"Rivian":["R1T","R1S"],"Subaru":["Impreza","WRX","BRZ","Crosstrek","Forester","Outback","Ascent","Solterra"],"Tesla":["Model 3","Model S","Model X","Model Y","Cybertruck"],"Toyota":["Corolla","Camry","Crown","Prius","GR86","Supra","Corolla Cross","RAV4","Highlander","Grand Highlander","4Runner","Land Cruiser","Sequoia","Tacoma","Tundra","Sienna","bZ4X"],"Volkswagen":["Jetta","Golf GTI","Golf R","Taos","Tiguan","Atlas","ID.4","ID. Buzz"],"Volvo":["S60","S90","XC40","XC60","XC90","EX30","EX90"]};
const EQUIPMENT_CATALOG={"Alpine":["Custom / Other","iLX-F511 Halo11","iLX-507"],"JL Audio":["Custom / Other","VX1000/5i","XD600/1v2","C3-650"],"Kicker":["Custom / Other","KEY 200.4","CXA800.1","KS Series"],"Kenwood":["Custom / Other","DMX958XR","DMX1057XR"],"Sony":["Custom / Other","XAV-9500ES","Mobile ES"],"Viper":["Custom / Other","DS4+","5706V","SmartStart"],"Compustar":["Custom / Other","CM-X","T13","DroneMobile"],"Escort":["Custom / Other","MAX 360c MKII","Redline Ci 360c"],"Uniden":["Custom / Other","R8","R7","R4"],"Thinkware":["Custom / Other","U3000","Q1000"],"BlackVue":["Custom / Other","DR970X","DR770X"],"XPEL":["Custom / Other","ULTIMATE PLUS","STEALTH","PRIME XR PLUS"],"3M":["Custom / Other","Crystalline","Ceramic IR","Scotchgard PPF"],"LLumar":["Custom / Other","IRX","CTX","Platinum PPF"],"Other / Customer supplied":["Custom / Other"]};
const SERVICE_CATALOG={
"Car stereo installation":{"Alpine":["Custom / Other","iLX-F511 Halo11","iLX-507"],"JL Audio":["Custom / Other","VX1000/5i","XD600/1v2","C3-650"],"Kicker":["Custom / Other","KEY 200.4","CXA800.1","KS Series"],"Kenwood":["Custom / Other","DMX958XR","DMX1057XR"],"Sony":["Custom / Other","XAV-9500ES","Mobile ES"],"Other / Customer supplied":["Custom / Other"]},
"Marine audio":{"JL Audio":["Custom / Other"],"Kicker":["Custom / Other"],"Kenwood":["Custom / Other"],"Sony":["Custom / Other"],"Other / Customer supplied":["Custom / Other"]},
"Car alarms":{"Viper":["Custom / Other","DS4+","5706V","SmartStart"],"Compustar":["Custom / Other","CM-X","T13","DroneMobile"],"Other / Customer supplied":["Custom / Other"]},
"Radar detectors":{"Escort":["Custom / Other","MAX 360c MKII","Redline Ci 360c"],"Uniden":["Custom / Other","R8","R7","R4"],"Other / Customer supplied":["Custom / Other"]},
"Dash cams":{"Thinkware":["Custom / Other","U3000","Q1000"],"BlackVue":["Custom / Other","DR970X","DR770X"],"Other / Customer supplied":["Custom / Other"]},
"Paint protection":{"XPEL":["Custom / Other","ULTIMATE PLUS","STEALTH"],"3M":["Custom / Other","Scotchgard PPF"],"LLumar":["Custom / Other","Platinum PPF"],"Other / Customer supplied":["Custom / Other"]},
"Window tint":{"XPEL":["Custom / Other","PRIME XR PLUS"],"3M":["Custom / Other","Crystalline","Ceramic IR"],"LLumar":["Custom / Other","IRX","CTX"],"Other / Customer supplied":["Custom / Other"]},
"GPS trackers":{"Compustar":["Custom / Other","DroneMobile"],"Viper":["Custom / Other","SmartStart"],"Other / Customer supplied":["Custom / Other"]},
"Interior lighting":{"Other / Customer supplied":["Custom / Other"]},
"Exterior lighting":{"Other / Customer supplied":["Custom / Other"]},
"Truck accessories":{"Other / Customer supplied":["Custom / Other"]},
"Other":{"Other / Customer supplied":["Custom / Other"]}
};
const TINT_PRODUCT_TECH={"PRIME XR PLUS":"IR Ceramic","Crystalline":"Multilayer Optical","Ceramic IR":"Ceramic","IRX":"IR Ceramic","CTX":"Ceramic"};
const TINT_TECH_MULTIPLIER={"Dyed":0.75,"Carbon":1,"Ceramic":1.35,"IR Ceramic":1.65,"Multilayer Optical":1.8,"Other":1};
const TINT_VLTS=["5%","15%","20%","25%","30%","35%","40%","50%","55%","70%","80%","Custom"];
const TINT_WINDOWS={
windshield:{label:"Windshield",material:85,labor:125},brow:{label:"Windshield brow / strip",material:12,labor:33},front_left:{label:"Driver front window",material:28,labor:52},front_right:{label:"Passenger front window",material:28,labor:52},rear_left:{label:"Left rear door",material:25,labor:45},rear_right:{label:"Right rear door",material:25,labor:45},quarter_left:{label:"Left quarter glass",material:12,labor:28},quarter_right:{label:"Right quarter glass",material:12,labor:28},rear_glass:{label:"Rear windshield",material:45,labor:75},sunroof:{label:"Sunroof",material:35,labor:65},panoramic:{label:"Panoramic roof",material:65,labor:105}
};
const TINT_PRESETS={"Front 2":["front_left","front_right"],"Rear section":["rear_left","rear_right","quarter_left","quarter_right","rear_glass"],"Full vehicle":["front_left","front_right","rear_left","rear_right","quarter_left","quarter_right","rear_glass"],"Full + windshield":["windshield","front_left","front_right","rear_left","rear_right","quarter_left","quarter_right","rear_glass"],"Windshield only":["windshield"]};

const seed={users:[{id:"usr_derek",name:"Derek Thompson",role:"owner_admin_technician"}],customers:[
{id:"cus_1",firstName:"Jordan",lastName:"Lee",name:"Jordan Lee",phone:"713-555-0184",email:"jordan@example.com",city:"Houston",state:"TX"},
{id:"cus_2",firstName:"Avery",lastName:"Martin",name:"Avery Martin",phone:"832-555-0117",email:"avery@example.com",city:"Houston",state:"TX"}],
vehicles:[
{id:"veh_1",customerId:"cus_1",vin:"1FTFW1E50RFA00001",year:"2024",make:"Ford",model:"F-150",trim:"Lariat",color:"Black",type:"Truck"},
{id:"veh_2",customerId:"cus_2",vin:"WBS43AZ09PCL00002",year:"2023",make:"BMW",model:"M4",trim:"Competition",color:"Blue",type:"Coupe"}],
jobs:[
{id:"J-260912-001",estimateId:"EST-260912-001",workOrderId:null,customerId:"cus_1",vehicleId:"veh_1",services:["Car stereo installation","Interior lighting"],equipment:[],requestNotes:"Premium audio upgrade with ambient lighting.",estimate:{parts:1750,labor:650,fees:50,deposit:500},estimateTotal:2450,status:"Scheduled",appointment:"2026-09-15T09:00",partsStatus:"Parts received",duration:"1 day",createdAt:"2026-09-12T14:00:00-05:00",createdBy:"usr_derek",audit:[]},
{id:"J-260911-002",estimateId:"EST-260911-002",workOrderId:"WO-260911-001",customerId:"cus_2",vehicleId:"veh_2",services:["Radar detectors","Dash cams"],equipment:[],requestNotes:"Hardwired radar and front/rear dashcam.",estimate:{parts:975,labor:350,fees:0,deposit:300},estimateTotal:1325,status:"In Progress",appointment:"2026-09-12T10:00",partsStatus:"Parts received",duration:"Same day",createdAt:"2026-09-11T11:40:00-05:00",createdBy:"usr_derek",checkIn:{odometer:"18320",fuel:"1/2",keys:"2 keys",belongings:"Sunglasses in console",warningLights:"None",conditionNotes:"Small curb rash RF wheel.",photos:[]},audit:[]}
],media:[],warranties:[]};

let db=load(),filter="All",currentJobId=null;
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(DB_KEY))||clone(seed)}catch{return clone(seed)}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function esc(v=""){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function money(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function uid(p){return p+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5)}
function customer(id){return db.customers.find(x=>x.id===id)}
function vehicle(id){return db.vehicles.find(x=>x.id===id)}
function job(id){return db.jobs.find(x=>x.id===id)}
function shortDate(v){return v?new Date(v).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—"}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav-item").forEach(v=>v.classList.toggle("active",v.dataset.view===id));const n=document.querySelector('.nav-item[data-view="'+id+'"]');document.getElementById("pageTitle").textContent=id==="newjob"?"New Job":id==="jobdetail"?"Job Details":(n?.textContent||"TTT OS");window.scrollTo({top:0,behavior:"smooth"});render()}
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>show(b.dataset.view));

function render(){renderStats();renderJobs();renderCustomers();renderVehicles();if(currentJobId)renderJobDetail()}
function renderStats(){const active=db.jobs.filter(j=>!["Closed","Declined"].includes(j.status));const inShop=db.jobs.filter(j=>["Checked In","Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts","QC","Ready for Pickup"].includes(j.status));document.getElementById("stats").innerHTML=[["Open jobs",active.length],["Vehicles in shop",inShop.length],["Ready for pickup",db.jobs.filter(j=>j.status==="Ready for Pickup").length],["Work orders",db.jobs.filter(j=>j.workOrderId).length]].map(([l,n])=>'<div class="stat"><span>'+l+'</span><strong>'+n+'</strong></div>').join("");
const groups=[["Lead / Estimate",["Lead","Estimate","Awaiting Approval"]],["Scheduled / Parts",["Scheduled","Awaiting Parts","Ready for Check-In"]],["In Shop",["Checked In","Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts"]],["QC / Delivery",["QC","Ready for Pickup","Delivered"]]];
document.getElementById("pipeline").innerHTML=groups.map(([l,ss])=>'<div class="pipeline-card"><span>'+l+'</span><strong>'+db.jobs.filter(j=>ss.includes(j.status)).length+'</strong></div>').join("");
const attention=db.jobs.filter(j=>["Awaiting Approval","Awaiting Parts","Ready for Check-In","Waiting on Customer","Waiting on Parts","Ready for Pickup"].includes(j.status)).slice(0,6);document.getElementById("attentionList").innerHTML=attention.length?attention.map(j=>'<button class="attention-row" onclick="openJob(\''+j.id+'\')"><div><strong>'+esc(j.id)+' · '+esc(customer(j.customerId)?.name)+'</strong><small>'+esc(vehicle(j.vehicleId)?.year+" "+vehicle(j.vehicleId)?.make+" "+vehicle(j.vehicleId)?.model)+'</small></div><span class="badge">'+esc(j.status)+'</span></button>').join(""):'<p class="muted">Nothing urgent right now.</p>'}
function renderJobs(){const filters=["All","Pre-Visit","In Shop","Delivery","Closed"];document.getElementById("jobFilters").innerHTML=filters.map(x=>'<button class="filter '+(filter===x?"active":"")+'" data-filter="'+x+'">'+x+'</button>').join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderJobs()});let rows=db.jobs.slice();if(filter==="Pre-Visit")rows=rows.filter(j=>["Lead","Estimate","Awaiting Approval","Scheduled","Awaiting Parts","Ready for Check-In"].includes(j.status));if(filter==="In Shop")rows=rows.filter(j=>["Checked In","Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts","QC"].includes(j.status));if(filter==="Delivery")rows=rows.filter(j=>["Ready for Pickup","Delivered"].includes(j.status));if(filter==="Closed")rows=rows.filter(j=>["Closed","Declined"].includes(j.status));document.getElementById("jobsBody").innerHTML=rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(j=>{const c=customer(j.customerId),v=vehicle(j.vehicleId);return '<tr><td><strong>'+esc(j.id)+'</strong>'+(j.workOrderId?'<br><small>'+esc(j.workOrderId)+'</small>':'')+'</td><td>'+esc(c?.name)+'</td><td>'+esc([v?.year,v?.make,v?.model].filter(Boolean).join(" "))+'</td><td>'+esc(j.services.join(", "))+'</td><td><span class="badge">'+esc(j.status)+'</span></td><td>'+shortDate(j.appointment)+'</td><td>'+money(j.estimateTotal)+'</td><td><button class="link-btn" onclick="openJob(\''+j.id+'\')">Open</button></td></tr>'}).join("")}
function renderCustomers(){document.getElementById("customersBody").innerHTML=db.customers.map(c=>'<tr><td><strong>'+esc(c.name)+'</strong></td><td>'+esc(c.phone)+'</td><td>'+esc(c.email)+'</td><td>'+db.vehicles.filter(v=>v.customerId===c.id).length+'</td><td>'+db.jobs.filter(j=>j.customerId===c.id).length+'</td></tr>').join("")}
function renderVehicles(){document.getElementById("vehiclesBody").innerHTML=db.vehicles.map(v=>{const js=db.jobs.filter(j=>j.vehicleId===v.id),last=js.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];return '<tr><td><strong>'+esc([v.year,v.make,v.model,v.trim].filter(Boolean).join(" "))+'</strong><br><small>'+esc(v.color||"")+'</small></td><td>'+esc(v.vin||"—")+'</td><td>'+esc(customer(v.customerId)?.name)+'</td><td>'+js.length+'</td><td>'+(last?'<span class="badge">'+esc(last.status)+'</span>':"—")+'</td></tr>').join("")}

window.openJob=function(id){currentJobId=id;show("jobdetail")}
function stageIndex(status){const order=["Lead","Estimate","Awaiting Approval","Scheduled","Ready for Check-In","Checked In","Awaiting Final Authorization","In Progress","QC","Ready for Pickup","Delivered","Closed"];return order.indexOf(status)}
function renderJobDetail(){const j=job(currentJobId);if(!j)return;const c=customer(j.customerId),v=vehicle(j.vehicleId);const stages=["Estimate","Scheduled","Check-In","Authorization","Work","QC","Delivery"];const idxMap={Lead:0,Estimate:0,"Awaiting Approval":0,Scheduled:1,"Awaiting Parts":1,"Ready for Check-In":1,"Checked In":2,"Awaiting Final Authorization":3,"In Progress":4,"Waiting on Customer":4,"Waiting on Parts":4,QC:5,"Ready for Pickup":6,Delivered:6,Closed:6};const sidx=idxMap[j.status]??0;
let body='<div class="detail-head"><div><button class="link-btn back-link" onclick="show(\'jobs\')">← Jobs</button><p class="eyebrow">'+esc(j.id)+(j.workOrderId?' · '+esc(j.workOrderId):' · NO WORK ORDER YET')+'</p><h2>'+esc([v?.year,v?.make,v?.model,v?.trim].filter(Boolean).join(" "))+'</h2><p>'+esc(c?.name)+' · '+esc(c?.phone||"")+'</p></div><div><span class="status-large">'+esc(j.status)+'</span></div></div>';
body+='<div class="workflow-track">'+stages.map((s,i)=>'<div class="workflow-step '+(i<sidx?"done":i===sidx?"current":"")+'"><span>'+(i<sidx?"✓":i+1)+'</span><small>'+s+'</small></div>').join("")+'</div>';
body+='<div class="detail-actions"><label>Status<select id="detailStatus">'+STATUSES.map(s=>'<option '+(s===j.status?"selected":"")+'>'+s+'</option>').join("")+'</select></label><button class="btn secondary" id="saveStatusBtn">Update status</button>'+nextActionButton(j)+'</div>';
body+='<div class="detail-grid"><article class="panel"><h3>Customer & vehicle</h3><dl class="detail-list"><dt>Customer</dt><dd>'+esc(c?.name)+'</dd><dt>Phone</dt><dd>'+esc(c?.phone)+'</dd><dt>Email</dt><dd>'+esc(c?.email||"—")+'</dd><dt>VIN</dt><dd>'+esc(v?.vin||"Not captured")+'</dd><dt>Vehicle</dt><dd>'+esc([v?.year,v?.make,v?.model,v?.trim].filter(Boolean).join(" "))+'</dd><dt>Color</dt><dd>'+esc(v?.color||"—")+'</dd></dl></article><article class="panel"><h3>Estimate</h3><dl class="detail-list"><dt>Estimate</dt><dd>'+esc(j.estimateId)+'</dd><dt>Parts</dt><dd>'+money(j.estimate.parts)+'</dd><dt>Labor</dt><dd>'+money(j.estimate.labor)+'</dd><dt>Other</dt><dd>'+money(j.estimate.fees)+'</dd><dt>Total</dt><dd><strong>'+money(j.estimateTotal)+'</strong></dd><dt>Deposit</dt><dd>'+money(j.estimate.deposit)+'</dd></dl></article></div>';
body+='<article class="panel detail-section"><div class="panel-head"><h3>Requested scope</h3><span class="badge">'+j.services.length+' service'+(j.services.length===1?"":"s")+'</span></div><p>'+esc(j.requestNotes)+'</p><div class="service-chips">'+j.services.map(s=>'<span>'+esc(s)+'</span>').join("")+'</div></article>';
if(["Ready for Check-In","Checked In","Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts","QC","Ready for Pickup","Delivered","Closed"].includes(j.status))body+=checkInBlock(j);
if(["Awaiting Final Authorization","In Progress","Waiting on Customer","Waiting on Parts","QC","Ready for Pickup","Delivered","Closed"].includes(j.status))body+=authorizationBlock(j);
if(j.workOrderId)body+=workOrderBlock(j);
document.getElementById("jobDetailBody").innerHTML=body;
document.getElementById("saveStatusBtn").onclick=()=>setStatus(document.getElementById("detailStatus").value);
const next=document.getElementById("nextActionBtn");if(next)next.onclick=()=>advanceJob(j);
const ci=document.getElementById("checkInForm");if(ci)ci.onsubmit=e=>saveCheckIn(e,j);
const auth=document.getElementById("authorizeBtn");if(auth)auth.onclick=()=>authorizeWork(j);
}
function nextActionButton(j){const map={"Lead":"Create Estimate","Estimate":"Send for Approval","Awaiting Approval":"Approve & Schedule","Scheduled":"Ready for Check-In","Awaiting Parts":"Ready for Check-In","Checked In":"Review Final Scope","In Progress":"Send to QC","QC":"Ready for Pickup","Ready for Pickup":"Mark Delivered","Delivered":"Close Job"};return map[j.status]?'<button class="btn primary" id="nextActionBtn">'+map[j.status]+'</button>':""}
function advanceJob(j){const map={"Lead":"Estimate","Estimate":"Awaiting Approval","Awaiting Approval":"Scheduled","Scheduled":"Ready for Check-In","Awaiting Parts":"Ready for Check-In","Checked In":"Awaiting Final Authorization","In Progress":"QC","QC":"Ready for Pickup","Ready for Pickup":"Delivered","Delivered":"Closed"};if(map[j.status])setStatus(map[j.status])}
function setStatus(status){const j=job(currentJobId);const old=j.status;j.status=status;j.updatedAt=new Date().toISOString();j.audit.push({at:j.updatedAt,actor:"usr_derek",action:"status_changed",from:old,to:status});save();render();toast("Status updated to "+status)}
function checkInBlock(j){const ci=j.checkIn||{};if(j.status==="Ready for Check-In")return '<article class="panel detail-section emphasis"><div class="panel-head"><div><h3>Vehicle Check-In</h3><p class="muted">TTT physical custody begins here. Document condition before work.</p></div><span class="badge">Protection checkpoint</span></div><form id="checkInForm"><div class="form-grid"><label>Odometer<input name="odometer" required></label><label>Fuel / charge<select name="fuel"><option>Empty / 0%</option><option>1/4</option><option>1/2</option><option>3/4</option><option>Full / 100%</option></select></label><label>Keys received<input name="keys" required></label><label>Warning lights / faults<input name="warningLights" placeholder="None, CEL, TPMS..."></label><label class="span-2">Personal belongings<textarea name="belongings"></textarea></label><label class="span-2">Condition / existing damage notes<textarea name="conditionNotes"></textarea></label></div><div class="checkin-media"><label>Walkaround / condition photos<input type="file" name="photos" accept="image/*" capture="environment" multiple></label><label>360° walkaround video<input type="file" name="video" accept="video/*" capture="environment"></label></div><button class="btn primary" type="submit">Complete Check-In</button></form></article>';
return '<article class="panel detail-section"><div class="panel-head"><h3>Check-In Record</h3><span class="badge">Recorded</span></div><dl class="detail-list two-col"><dt>Odometer</dt><dd>'+esc(ci.odometer||"—")+'</dd><dt>Fuel / charge</dt><dd>'+esc(ci.fuel||"—")+'</dd><dt>Keys</dt><dd>'+esc(ci.keys||"—")+'</dd><dt>Warning lights</dt><dd>'+esc(ci.warningLights||"None")+'</dd><dt>Belongings</dt><dd>'+esc(ci.belongings||"None noted")+'</dd><dt>Condition notes</dt><dd>'+esc(ci.conditionNotes||"None noted")+'</dd></dl></article>'}
function saveCheckIn(e,j){e.preventDefault();const fd=new FormData(e.currentTarget),now=new Date().toISOString();j.checkIn={odometer:fd.get("odometer"),fuel:fd.get("fuel"),keys:fd.get("keys"),warningLights:fd.get("warningLights"),belongings:fd.get("belongings"),conditionNotes:fd.get("conditionNotes"),capturedAt:now,photoCount:e.currentTarget.photos.files.length,hasVideo:!!e.currentTarget.video.files.length};j.status="Checked In";j.audit.push({at:now,actor:"usr_derek",action:"vehicle_checked_in"});save();render();toast("Vehicle checked in")}
function authorizationBlock(j){if(j.status==="Awaiting Final Authorization")return '<article class="panel detail-section emphasis"><div class="panel-head"><div><h3>Final Authorization</h3><p class="muted">Confirm scope after physical inspection. This is the point a Work Order is created.</p></div><span class="badge">Customer approval</span></div><div class="authorization-summary"><p><strong>Estimate:</strong> '+money(j.estimateTotal)+'</p><p><strong>Inspection:</strong> '+esc(j.checkIn?.conditionNotes||"No additional condition notes")+'</p><label class="consent"><input type="checkbox" id="finalAuthCheck"> Customer approves the final scope, estimate and inspection findings.</label><label>Customer authorized by<input id="finalAuthName" placeholder="Customer full name"></label><button class="btn primary top-gap" id="authorizeBtn">Authorize & Create Work Order</button></div></article>';if(j.finalAuthorization)return '<article class="panel detail-section"><div class="panel-head"><h3>Final Authorization</h3><span class="badge">Signed</span></div><p>Authorized by <strong>'+esc(j.finalAuthorization.name)+'</strong> · '+new Date(j.finalAuthorization.at).toLocaleString()+'</p></article>';return ""}
function authorizeWork(j){if(!document.getElementById("finalAuthCheck").checked||!document.getElementById("finalAuthName").value.trim()){toast("Customer authorization is required");return}const now=new Date().toISOString();j.finalAuthorization={name:document.getElementById("finalAuthName").value.trim(),at:now,termsVersion:"0.2"};j.workOrderId="WO-"+new Date().toISOString().slice(2,10).replaceAll("-","")+"-"+String(db.jobs.filter(x=>x.workOrderId).length+1).padStart(3,"0");j.status="In Progress";j.audit.push({at:now,actor:"usr_derek",action:"final_authorization_and_work_order_created",workOrderId:j.workOrderId});save();render();toast(j.workOrderId+" created")}
function workOrderBlock(j){return '<article class="panel detail-section workorder-card"><div class="panel-head"><div><p class="eyebrow">ACTIVE WORK ORDER</p><h3>'+esc(j.workOrderId)+'</h3></div><span class="badge">'+esc(j.status)+'</span></div><div class="work-tabs"><span>Overview</span><span>Parts / Equipment</span><span>Progress</span><span>Change Orders</span><span>QC</span><span>Delivery</span><span>Warranty</span></div><p class="muted">The work-order execution tabs are now correctly downstream of check-in and final customer authorization. These are the next modules to deepen.</p></article>'}

const stateSel=document.getElementById("stateSelect");stateSel.innerHTML='<option value="">State</option>'+STATES.map(s=>'<option '+(s==="TX"?"selected":"")+'>'+s+'</option>').join("");
const yearSelect=document.getElementById("yearSelect"),makeSelect=document.getElementById("makeSelect"),modelSelect=document.getElementById("modelSelect"),yearOther=document.getElementById("yearOther"),makeOther=document.getElementById("makeOther"),modelOther=document.getElementById("modelOther");
function populateVehicleSelectors(){yearSelect.innerHTML='<option value="">Year</option>';for(let y=new Date().getFullYear()+1;y>=1981;y--)yearSelect.insertAdjacentHTML("beforeend",'<option>'+y+'</option>');yearSelect.insertAdjacentHTML("beforeend",'<option value="__other">Other</option>');makeSelect.innerHTML='<option value="">Make</option>'+Object.keys(VEHICLE_CATALOG).map(x=>'<option>'+x+'</option>').join("")+'<option value="__other">Other / Not listed</option>';loadModels()}
function loadModels(preferred=""){const make=resolved("make");modelSelect.innerHTML='<option value="">Model</option>'+((VEHICLE_CATALOG[make]||[]).map(x=>'<option>'+x+'</option>').join(""))+'<option value="__other">Other / Not listed</option>';if(preferred)setSelect(modelSelect,preferred,modelOther)}
function bindOther(sel,input){sel.onchange=()=>{input.classList.toggle("hidden",sel.value!=="__other");if(sel===makeSelect)loadModels()}}
bindOther(yearSelect,yearOther);bindOther(makeSelect,makeOther);bindOther(modelSelect,modelOther);populateVehicleSelectors();
function resolved(name){const s=document.querySelector('[name="'+name+'"]'),o=document.querySelector('[name="'+name+'Other"]');return s.value==="__other"?(o?.value||""):s.value}
function setSelect(sel,val,other){if(!val)return;let o=[...sel.options].find(x=>x.textContent.toLowerCase()===String(val).toLowerCase());if(!o){o=document.createElement("option");o.textContent=val;o.value=val;sel.insertBefore(o,sel.querySelector('[value="__other"]'))}sel.value=o.value;other.classList.add("hidden")}
function normVin(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").replace(/[IOQ]/g,"").slice(0,17)}
const vinInput=document.getElementById("vinInput"),vinStatus=document.getElementById("vinScanStatus"),vinPhotoInput=document.getElementById("vinPhotoInput"),vinPhotoPreview=document.getElementById("vinPhotoPreview");
vinInput.oninput=()=>vinInput.value=normVin(vinInput.value);
function vinMsg(m,c=""){vinStatus.textContent=m;vinStatus.className="vin-status "+c}
async function decodeVin(){const vin=normVin(vinInput.value);if(vin.length!==17){vinMsg("Enter a complete 17-character VIN.","warn");return}vinMsg("Decoding VIN…","working");try{const d=(await (await fetch("https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/"+vin+"?format=json")).json()).Results[0];if(d.ModelYear)setSelect(yearSelect,d.ModelYear,yearOther);if(d.Make)setSelect(makeSelect,d.Make,makeOther);loadModels(d.Model);if(d.Trim||d.Series)document.getElementById("trimInput").value=d.Trim||d.Series;const b=(d.BodyClass||"").toLowerCase(),t=b.includes("pickup")?"Truck":b.includes("utility")?"SUV":b.includes("coupe")?"Coupe":b.includes("sedan")?"Sedan":b.includes("van")?"Van":"";if(t)document.getElementById("vehicleTypeSelect").value=t;vinMsg("✓ VIN decoded. Please verify the vehicle details.","success")}catch{vinMsg("VIN decoder unavailable. Manual entry still works.","error")}}
document.getElementById("decodeVinBtn").onclick=decodeVin;
vinPhotoInput.onchange=async()=>{const f=vinPhotoInput.files[0];if(!f)return;vinPhotoPreview.innerHTML='<img src="'+URL.createObjectURL(f)+'">';vinMsg("Reading VIN photo…","working");try{const r=await Tesseract.recognize(f,"eng");const matches=String(r.data.text).toUpperCase().match(/[A-HJ-NPR-Z0-9]{17}/g)||[];if(matches[0]){vinInput.value=matches[0];decodeVin()}else vinMsg("Could not confidently read the VIN. Try another photo or enter it manually.","warn")}catch{vinMsg("VIN scan failed. Manual entry still works.","error")}};

const serviceRows=document.getElementById("serviceRows");
function catalogForService(service){return SERVICE_CATALOG[service]||{"Other / Customer supplied":["Custom / Other"]}}
function tintWindowMarkup(){return Object.entries(TINT_WINDOWS).map(([key,w])=>'<label class="tint-window"><span><input type="checkbox" data-tint-window="'+key+'"> '+w.label+'</span><select data-tint-vlt="'+key+'">'+TINT_VLTS.map(v=>'<option '+(v==="35%"?'selected':'')+'>'+v+'</option>').join('')+'</select></label>').join('')}
function addServiceRow(values={}){const row=document.createElement("div");row.className="equipment-row";row.innerHTML='<label>Service<select data-eq="category"><option value="">Select service</option>'+SERVICES.map(s=>'<option '+(values.category===s?"selected":"")+'>'+s+'</option>').join("")+'</select></label><label>Brand<select data-eq="brand" disabled><option value="">Select service first</option></select></label><label>Product / model<select data-eq="model" disabled><option value="">Select brand first</option></select></label><label>Qty<input data-eq="qty" type="number" min="1" value="'+(values.qty||1)+'"></label><label class="equipment-note">Line notes<input data-eq="note" value="'+esc(values.note||'')+'" placeholder="Variant, location, customer-supplied..."></label><button type="button" class="remove-equipment">×</button><div class="tint-config hidden" data-tint-config><div class="tint-config-head"><div><strong>Window tint configuration</strong><span>Select the glass, film technology and VLT for a quote-ready scope.</span></div><span class="badge">Smart estimate</span></div><div class="tint-grid"><label>Film technology<select data-tint="technology"><option>Dyed</option><option>Carbon</option><option selected>Ceramic</option><option>IR Ceramic</option><option>Multilayer Optical</option><option>Other</option></select></label><label>Default VLT<select data-tint="defaultVlt">'+TINT_VLTS.map(v=>'<option '+(v==="35%"?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Existing tint removal<select data-tint="removal"><option value="none">None</option><option value="selected">Needed on selected glass</option><option value="unknown">Unknown / inspect</option></select></label></div><div class="tint-presets">'+Object.keys(TINT_PRESETS).map(p=>'<button type="button" class="tint-preset" data-tint-preset="'+p+'">'+p+'</button>').join('')+'<button type="button" class="tint-preset" data-tint-preset="Clear">Clear</button></div><div class="tint-window-grid">'+tintWindowMarkup()+'</div><div class="tint-estimate"><div><span>Estimated materials</span><strong data-tint-estimate="parts">$0.00</strong></div><div><span>Estimated labor</span><strong data-tint-estimate="labor">$0.00</strong></div><div><span>Suggested range</span><strong data-tint-estimate="range">$0–$0</strong></div><button type="button" class="btn secondary compact" data-tint-apply>Use midpoint as draft</button></div><p class="tint-disclaimer">Starter internal estimator only. Pricing rules are structured so they can be replaced by TTT's validated film costs, labor standards, dealer tiers and market pricing library.</p></div>';serviceRows.appendChild(row);
const c=row.querySelector('[data-eq="category"]'),b=row.querySelector('[data-eq="brand"]'),m=row.querySelector('[data-eq="model"]'),tint=row.querySelector('[data-tint-config]');
function refreshBrands(preferred=''){const catalog=catalogForService(c.value);const brands=Object.keys(catalog);b.disabled=!c.value;b.innerHTML='<option value="">'+(c.value?'Select brand':'Select service first')+'</option>'+brands.map(x=>'<option>'+x+'</option>').join('');if(preferred&&brands.includes(preferred))b.value=preferred;refreshModels(values.model||'');tint.classList.toggle('hidden',c.value!=="Window tint");updateTintEstimate(row)}
function refreshModels(preferred=''){const catalog=catalogForService(c.value);const models=catalog[b.value]||[];m.disabled=!b.value;m.innerHTML='<option value="">'+(b.value?'Select model':'Select brand first')+'</option>'+models.map(x=>'<option>'+x+'</option>').join('');if(preferred&&models.includes(preferred))m.value=preferred;if(c.value==="Window tint"&&TINT_PRODUCT_TECH[m.value])row.querySelector('[data-tint="technology"]').value=TINT_PRODUCT_TECH[m.value];updateTintEstimate(row)}
c.onchange=()=>{refreshBrands();};b.onchange=()=>refreshModels();m.onchange=()=>{if(c.value==="Window tint"&&TINT_PRODUCT_TECH[m.value])row.querySelector('[data-tint="technology"]').value=TINT_PRODUCT_TECH[m.value];updateTintEstimate(row)};
row.querySelector('[data-tint="defaultVlt"]').onchange=e=>{row.querySelectorAll('[data-tint-window]:checked').forEach(cb=>{const s=row.querySelector('[data-tint-vlt="'+cb.dataset.tintWindow+'"]');if(s)s.value=e.target.value});updateTintEstimate(row)};
row.querySelectorAll('[data-tint-window],[data-tint-vlt],[data-tint]').forEach(el=>el.onchange=()=>updateTintEstimate(row));
row.querySelectorAll('[data-tint-preset]').forEach(btn=>btn.onclick=()=>{const keys=TINT_PRESETS[btn.dataset.tintPreset]||[];row.querySelectorAll('[data-tint-window]').forEach(cb=>cb.checked=keys.includes(cb.dataset.tintWindow));const d=row.querySelector('[data-tint="defaultVlt"]').value;row.querySelectorAll('[data-tint-window]:checked').forEach(cb=>row.querySelector('[data-tint-vlt="'+cb.dataset.tintWindow+'"]').value=d);updateTintEstimate(row)});
row.querySelector('[data-tint-apply]').onclick=()=>{const q=calculateTintEstimate(row);document.querySelector('[name="parts"]').value=q.parts.toFixed(2);document.querySelector('[name="labor"]').value=q.labor.toFixed(2);updateTotal();toast('Tint estimate applied to draft pricing')};
row.querySelector(".remove-equipment").onclick=()=>row.remove();refreshBrands(values.brand||'');if(values.category==="Window tint"&&values.tintConfig)restoreTintConfig(row,values.tintConfig)}
function calculateTintEstimate(row){const tech=row.querySelector('[data-tint="technology"]')?.value||"Other",mult=TINT_TECH_MULTIPLIER[tech]||1,vehicleType=document.getElementById('vehicleTypeSelect')?.value||'Sedan',laborMult={Sedan:1,Coupe:1.05,SUV:1.12,Truck:1.08,Van:1.2,Marine:1.25,Other:1}[vehicleType]||1,removal=row.querySelector('[data-tint="removal"]')?.value||'none';let parts=0,labor=0,count=0;row.querySelectorAll('[data-tint-window]:checked').forEach(cb=>{const w=TINT_WINDOWS[cb.dataset.tintWindow];if(!w)return;count++;parts+=w.material*mult;labor+=w.labor*laborMult});if(removal==='selected')labor+=count*25;return{parts:Math.round(parts),labor:Math.round(labor),total:Math.round(parts+labor),low:Math.round((parts+labor)*.9),high:Math.round((parts+labor)*1.1)}}
function readTintConfig(row){if(row.querySelector('[data-eq="category"]')?.value!=="Window tint")return null;const windows=[...row.querySelectorAll('[data-tint-window]:checked')].map(cb=>({key:cb.dataset.tintWindow,label:TINT_WINDOWS[cb.dataset.tintWindow]?.label||cb.dataset.tintWindow,vlt:row.querySelector('[data-tint-vlt="'+cb.dataset.tintWindow+'"]')?.value||''})),q=calculateTintEstimate(row);return{technology:row.querySelector('[data-tint="technology"]')?.value||'',defaultVlt:row.querySelector('[data-tint="defaultVlt"]')?.value||'',removal:row.querySelector('[data-tint="removal"]')?.value||'none',windows,estimate:q}}
function restoreTintConfig(row,cfg){if(cfg.technology)row.querySelector('[data-tint="technology"]').value=cfg.technology;if(cfg.defaultVlt)row.querySelector('[data-tint="defaultVlt"]').value=cfg.defaultVlt;if(cfg.removal)row.querySelector('[data-tint="removal"]').value=cfg.removal;(cfg.windows||[]).forEach(w=>{const cb=row.querySelector('[data-tint-window="'+w.key+'"]'),sel=row.querySelector('[data-tint-vlt="'+w.key+'"]');if(cb)cb.checked=true;if(sel&&w.vlt)sel.value=w.vlt});updateTintEstimate(row)}
function updateTintEstimate(row){if(row.querySelector('[data-eq="category"]')?.value!=="Window tint")return;const q=calculateTintEstimate(row),cfg=readTintConfig(row);row.querySelector('[data-tint-estimate="parts"]').textContent=money(q.parts);row.querySelector('[data-tint-estimate="labor"]').textContent=money(q.labor);row.querySelector('[data-tint-estimate="range"]').textContent=money(q.low)+' – '+money(q.high);const note=row.querySelector('[data-eq="note"]');if(note&&cfg.windows.length){const film=[row.querySelector('[data-eq="brand"]').value,row.querySelector('[data-eq="model"]').value,cfg.technology].filter(Boolean).join(' · '),glass=cfg.windows.map(w=>w.label+' '+w.vlt).join(', ');note.value=(film?film+' | ':'')+glass+(cfg.removal==='selected'?' | Remove existing tint':'')+(cfg.removal==='unknown'?' | Existing tint TBD':'')}}
document.getElementById("addServiceBtn").onclick=()=>addServiceRow();addServiceRow();document.getElementById('vehicleTypeSelect').addEventListener('change',()=>document.querySelectorAll('.equipment-row').forEach(r=>updateTintEstimate(r)));
["parts","labor","fees"].forEach(n=>document.querySelector('[name="'+n+'"]').oninput=updateTotal);function updateTotal(){const f=document.getElementById("jobForm");document.getElementById("estimateTotal").textContent=money(["parts","labor","fees"].reduce((s,n)=>s+Number(f.elements[n].value||0),0))}
document.getElementById("jobForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),now=new Date().toISOString(),full=[fd.get("firstName"),fd.get("middleName"),fd.get("lastName")].filter(Boolean).join(" ");let c=db.customers.find(x=>x.email&&fd.get("email")&&x.email.toLowerCase()===fd.get("email").toLowerCase());if(!c){c={id:uid("cus"),firstName:fd.get("firstName"),middleName:fd.get("middleName"),lastName:fd.get("lastName"),name:full,phone:fd.get("phone"),email:fd.get("email"),address1:fd.get("address1"),address2:fd.get("address2"),city:fd.get("city"),state:fd.get("state"),postalCode:fd.get("postalCode"),country:fd.get("country"),notes:fd.get("customerNotes")};db.customers.push(c)}let v=db.vehicles.find(x=>fd.get("vin")&&x.vin===fd.get("vin"));if(!v){v={id:uid("veh"),customerId:c.id,vin:fd.get("vin"),year:resolved("year"),make:resolved("make"),model:resolved("model"),trim:fd.get("trim"),color:fd.get("color"),wrap:fd.get("wrap"),type:fd.get("vehicleType"),plate:fd.get("plate")};db.vehicles.push(v)}const equipment=[...document.querySelectorAll(".equipment-row")].map(r=>({category:r.querySelector('[data-eq="category"]').value,brand:r.querySelector('[data-eq="brand"]').value,model:r.querySelector('[data-eq="model"]').value,qty:Number(r.querySelector('[data-eq="qty"]').value||1),note:r.querySelector('[data-eq="note"]').value,tintConfig:readTintConfig(r)})).filter(x=>x.category||x.brand||x.model);const parts=+fd.get("parts")||0,labor=+fd.get("labor")||0,fees=+fd.get("fees")||0,num=db.jobs.length+1,date=new Date().toISOString().slice(2,10).replaceAll("-","");const j={id:"J-"+date+"-"+String(num).padStart(3,"0"),estimateId:"EST-"+date+"-"+String(num).padStart(3,"0"),workOrderId:null,customerId:c.id,vehicleId:v.id,services:[...new Set(equipment.map(x=>x.category).filter(Boolean))],equipment,requestNotes:fd.get("requestNotes"),estimate:{parts,labor,fees,deposit:+fd.get("deposit")||0},estimateTotal:parts+labor+fees,status:fd.get("initialStatus"),appointment:fd.get("appointment"),partsStatus:fd.get("partsStatus"),duration:fd.get("duration"),createdAt:now,createdBy:"usr_derek",audit:[{at:now,actor:"usr_derek",action:"job_created"}]};db.jobs.push(j);save();e.currentTarget.reset();serviceRows.innerHTML="";addServiceRow();populateVehicleSelectors();updateTotal();currentJobId=j.id;show("jobdetail");toast(j.id+" created")};
document.getElementById("seedBtn").onclick=()=>{db=clone(seed);save();filter="All";currentJobId=null;render();show("dashboard");toast("Demo reset")};
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}
render();