(function(){
'use strict';
const byId=id=>document.getElementById(id),cloud=()=>window.TTTCloud;let pendingFactor=null;
function styles(){if(byId('tttMfaStyles'))return;const s=document.createElement('style');s.id='tttMfaStyles';s.textContent=`
.mfa-status{display:inline-flex;border-radius:999px;padding:5px 9px;font-size:10px;font-weight:850;background:#f2f4f7;color:#475467}.mfa-status.on{background:#ecfdf3;color:#027a48}.mfa-status.required{background:#fff7ed;color:#c2410c}.mfa-setup{margin-top:14px;padding:14px;border:1px solid #dce6f2;border-radius:12px;background:#f8fafc}.mfa-setup img{width:190px;max-width:100%;display:block;margin:12px 0;border:8px solid #fff;border-radius:10px}.mfa-secret{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;word-break:break-all;background:#fff;border:1px solid #dde5ef;border-radius:8px;padding:9px}.mfa-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.mfa-code{max-width:180px;min-height:40px;border:1px solid #d6deea;border-radius:9px;padding:8px 10px;font:inherit}.mfa-message{font-size:12px;color:#66758a;margin-top:8px}.mfa-message.error{color:#b42318}.mfa-message.ok{color:#027a48}`;document.head.appendChild(s);}
function card(){const layout=document.querySelector('#myaccount .account-layout');if(!layout)return null;let el=byId('mfaAccountCard');if(!el){el=document.createElement('article');el.className='panel';el.id='mfaAccountCard';layout.appendChild(el);}return el;}
function message(text,kind=''){const el=byId('mfaMessage');if(!el)return;el.textContent=text;el.className='mfa-message '+kind;}
async function refresh(){const c=cloud(),el=card();if(!c?.client||!c?.userId||!el)return;try{const factors=await c.client.auth.mfa.listFactors();if(factors.error)throw factors.error;const aal=await c.client.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error)throw aal.error;const verified=(factors.data?.totp||[]).filter(x=>x.status==='verified'),required=c.profile?.role==='owner_admin';el.innerHTML=`
<div class="panel-head"><div><h3>Multi-factor authentication</h3><p class="muted">Use an authenticator app as a second factor for TTT OS.</p></div><span class="mfa-status ${verified.length?'on':required?'required':''}">${verified.length?'Enabled':required?'Admin setup required':'Available'}</span></div>
${verified.length?'<p><strong>'+verified.length+' authenticator factor'+(verified.length===1?'':'s')+' enrolled.</strong></p><p class="muted">Current session assurance: '+String(aal.data?.currentLevel||'unknown').toUpperCase()+'. A backup factor is recommended.</p>':'<p class="muted">'+(required?'Administrator accounts should enable MFA before regular use.':'MFA is optional for this account.')+'</p>'}
<div class="mfa-row"><button class="btn ${verified.length?'secondary':'primary'} compact" id="mfaEnroll" type="button">${verified.length?'+ Add backup factor':'Enable authenticator MFA'}</button><button class="btn secondary compact" id="mfaSignOutOthers" type="button">Sign out all other devices</button></div><div id="mfaSetupArea"></div><div id="mfaMessage" class="mfa-message"></div>`;byId('mfaEnroll')?.addEventListener('click',startEnroll);byId('mfaSignOutOthers')?.addEventListener('click',signOutOthers);}catch{el.innerHTML='<h3>Multi-factor authentication</h3><p class="muted">MFA status could not be loaded.</p>';}}
async function startEnroll(){const c=cloud();if(!c?.client)return;message('Creating authenticator setup…');try{const {data,error}=await c.client.auth.mfa.enroll({factorType:'totp',friendlyName:'TTT OS Authenticator'});if(error)throw error;pendingFactor=data.id;byId('mfaSetupArea').innerHTML=`<div class="mfa-setup"><strong>1. Scan this QR code</strong><p class="muted">Use Apple Passwords, Google Authenticator, Microsoft Authenticator, Authy, 1Password, or another TOTP app.</p><img src="${data.totp.qr_code}" alt="Authenticator QR code"><div class="mfa-secret">${data.totp.secret||''}</div><p><strong>2. Enter the 6-digit code</strong></p><div class="mfa-row"><input id="mfaVerifyCode" class="mfa-code" inputmode="numeric" autocomplete="one-time-code" maxlength="8" placeholder="123456"><button class="btn primary compact" id="mfaVerifyBtn" type="button">Verify & enable</button><button class="btn secondary compact" id="mfaCancelBtn" type="button">Cancel</button></div><p class="muted">When enrollment is verified, Supabase signs out the account's other sessions as a security precaution.</p></div>`;byId('mfaVerifyBtn')?.addEventListener('click',verifyEnroll);byId('mfaCancelBtn')?.addEventListener('click',cancelEnroll);message('');}catch(error){message(error?.message||'MFA setup could not be started.','error');}}
async function verifyEnroll(){const c=cloud(),code=byId('mfaVerifyCode')?.value.trim();if(!c?.client||!pendingFactor||!code)return;message('Verifying…');try{const challenge=await c.client.auth.mfa.challenge({factorId:pendingFactor});if(challenge.error)throw challenge.error;const verify=await c.client.auth.mfa.verify({factorId:pendingFactor,challengeId:challenge.data.id,code});if(verify.error)throw verify.error;pendingFactor=null;message('MFA enabled successfully.','ok');setTimeout(refresh,500);}catch(error){message(error?.message||'The authenticator code was not accepted.','error');}}
async function cancelEnroll(){if(!pendingFactor){refresh();return;}try{await cloud()?.client?.auth?.mfa?.unenroll({factorId:pendingFactor});}catch{}pendingFactor=null;refresh();}
async function signOutOthers(){const c=cloud();if(!c?.client)return;message('Signing out other sessions…');const {error}=await c.client.auth.signOut({scope:'others'});message(error?error.message:'All other TTT OS sessions have been signed out.',error?'error':'ok');window.dispatchEvent(new CustomEvent('ttt:security-event-recorded'));}
function init(){styles();refresh();window.addEventListener('ttt:cloud-state-applied',refresh);window.addEventListener('ttt:account-updated',refresh);}window.TTTMFA={refresh};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();