// TTT OS v0.3 — quotation and customer approval workflow
(function(){
  const QUOTE_TEMPLATE_URL='https://docs.google.com/document/d/14_fS3C6JBDQ4rwyxTBzjGcmQWEJenpthEUmqYndOijk/edit';
  if(!STATUSES.includes('Awaiting Deposit')) STATUSES.splice(Math.max(STATUSES.indexOf('Scheduled'),0),0,'Awaiting Deposit');
  const LABELS={Lead:'Job Draft',Estimate:'Quote Draft','Awaiting Approval':'Awaiting Approval','Awaiting Deposit':'Awaiting Deposit',Scheduled:'Scheduled','Awaiting Parts':'Awaiting Parts','Ready for Check-In':'Ready for Check-In','Checked In':'Checked In','Awaiting Final Authorization':'Awaiting Final Authorization','In Progress':'In Progress','Waiting on Customer':'Waiting on Customer','Waiting on Parts':'Waiting on Parts',QC:'QC','Ready for Pickup':'Ready for Pickup',Delivered:'Delivered',Closed:'Closed',Declined:'Declined'};
  const displayStatus=s=>LABELS[s]||s;
  const year=()=>new Date().getFullYear();
  const seq=(kind)=>{let max=0;db.jobs.forEach(j=>{const values=kind==='quote'?[j.quote?.id,j.quoteId]:kind==='approval'?[j.quote?.approval?.id,j.finalAuthorization?.id]:[j.workOrderId];values.filter(Boolean).forEach(v=>{const m=String(v).match(/-(\d{4})$/);if(m)max=Math.max(max,+m[1])})});return String(max+1).padStart(4,'0')};
  const newQuoteId=()=>`Q-${year()}-${seq('quote')}`;
  const newApprovalId=()=>`APR-${year()}-${seq('approval')}`;
  const newWorkOrderId=()=>`WO-${year()}-${seq('wo')}`;

  function touch(j,action,extra={}){const at=new Date().toISOString();j.updatedAt=at;j.syncState='pending';j.audit=j.audit||[];j.audit.push({at,actor:'usr_derek',action,...extra});save()}
  function snapshot(j){const c=customer(j.customerId)||{},v=vehicle(j.vehicleId)||{};return{customer:{name:c.name||'',phone:c.phone||'',email:c.email||''},vehicle:{vin:v.vin||'',year:v.year||'',make:v.make||'',model:v.model||'',trim:v.trim||'',color:v.color||''},services:[...(j.services||[])],equipment:(j.equipment||[]).map(x=>({...x})),requestNotes:j.requestNotes||'',estimate:{...(j.estimate||{})},estimateTotal:+j.estimateTotal||0,appointment:j.appointment||'',duration:j.duration||''}}

  function prepNewJob(){const f=document.getElementById('jobForm');if(!f)return;const s=f.querySelector('[name="initialStatus"]');if(s){s.innerHTML='<option value="Lead" selected>Job Draft</option>';s.disabled=false}const h=f.querySelector('.form-section:nth-of-type(3) .form-copy h3');if(h)h.textContent='Requested work & draft pricing';const p=f.querySelector('.form-section:nth-of-type(3) .form-copy p');if(p)p.textContent='Capture the customer request and draft pricing. Generate the formal quotation from the job after review.';const note=f.querySelector('.submit-bar span');if(note)note.textContent='Creates a Job Draft. The quotation is generated and approved from the job page.'}

  renderJobs=function(){
    const filters=['All','Pre-Visit','In Shop','Delivery','Closed'];
    document.getElementById('jobFilters').innerHTML=filters.map(x=>'<button class="filter '+(filter===x?'active':'')+'" data-filter="'+x+'">'+x+'</button>').join('');
    document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderJobs()});
    let rows=db.jobs.slice();
    if(filter==='Pre-Visit')rows=rows.filter(j=>['Lead','Estimate','Awaiting Approval','Awaiting Deposit','Scheduled','Awaiting Parts','Ready for Check-In'].includes(j.status));
    if(filter==='In Shop')rows=rows.filter(j=>['Checked In','Awaiting Final Authorization','In Progress','Waiting on Customer','Waiting on Parts','QC'].includes(j.status));
    if(filter==='Delivery')rows=rows.filter(j=>['Ready for Pickup','Delivered'].includes(j.status));
    if(filter==='Closed')rows=rows.filter(j=>['Closed','Declined'].includes(j.status));
    document.getElementById('jobsBody').innerHTML=rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(j=>{const c=customer(j.customerId),v=vehicle(j.vehicleId);return '<tr><td><strong>'+esc(j.id)+'</strong>'+(j.quote?.id?'<br><small>'+esc(j.quote.id)+'</small>':'')+(j.workOrderId?'<br><small>'+esc(j.workOrderId)+'</small>':'')+'</td><td>'+esc(c?.name)+'</td><td>'+esc([v?.year,v?.make,v?.model].filter(Boolean).join(' '))+'</td><td>'+esc((j.services||[]).join(', '))+'</td><td><span class="badge">'+esc(displayStatus(j.status))+'</span></td><td>'+shortDate(j.appointment)+'</td><td>'+money(j.estimateTotal)+'</td><td><button class="link-btn" onclick="openJob(\''+j.id+'\')">Open</button></td></tr>'}).join('');
  };

  renderJobDetail=function(){const j=job(currentJobId);if(!j)return;const c=customer(j.customerId)||{},v=vehicle(j.vehicleId)||{};const stages=['Job','Quote','Approval','Schedule','Check-In','Authorization','Work','QC','Delivery'];const map={Lead:0,Estimate:1,'Awaiting Approval':2,'Awaiting Deposit':3,Scheduled:3,'Awaiting Parts':3,'Ready for Check-In':3,'Checked In':4,'Awaiting Final Authorization':5,'In Progress':6,'Waiting on Customer':6,'Waiting on Parts':6,QC:7,'Ready for Pickup':8,Delivered:8,Closed:8,Declined:8};const idx=map[j.status]??0;
    let body='<div class="detail-head"><div><button class="link-btn back-link" onclick="show(\'jobs\')">← Jobs</button><p class="eyebrow">'+esc(j.id)+(j.quote?.id?' · '+esc(j.quote.id):' · NO QUOTE YET')+(j.workOrderId?' · '+esc(j.workOrderId):'')+'</p><h2>'+esc([v.year,v.make,v.model,v.trim].filter(Boolean).join(' '))+'</h2><p>'+esc(c.name||'')+' · '+esc(c.phone||'')+'</p></div><div><span class="status-large">'+esc(displayStatus(j.status))+'</span></div></div>';
    body+='<div class="workflow-track workflow-track-v3">'+stages.map((s,i)=>'<div class="workflow-step '+(i<idx?'done':i===idx?'current':'')+'"><span>'+(i<idx?'✓':i+1)+'</span><small>'+s+'</small></div>').join('')+'</div>';
    body+='<div class="detail-actions"><label>Status<select id="detailStatus">'+STATUSES.map(s=>'<option value="'+esc(s)+'" '+(s===j.status?'selected':'')+'>'+esc(displayStatus(s))+'</option>').join('')+'</select></label><button class="btn secondary" id="saveStatusBtn">Update status</button>'+nextButton(j)+'</div>';
    body+='<div class="detail-grid"><article class="panel"><h3>Customer & vehicle</h3><dl class="detail-list"><dt>Customer</dt><dd>'+esc(c.name||'')+'</dd><dt>Phone</dt><dd>'+esc(c.phone||'')+'</dd><dt>Email</dt><dd>'+esc(c.email||'—')+'</dd><dt>VIN</dt><dd>'+esc(v.vin||'Not captured')+'</dd><dt>Vehicle</dt><dd>'+esc([v.year,v.make,v.model,v.trim].filter(Boolean).join(' '))+'</dd><dt>Color</dt><dd>'+esc(v.color||'—')+'</dd></dl></article><article class="panel"><h3>Draft pricing</h3><dl class="detail-list"><dt>Parts</dt><dd>'+money(j.estimate?.parts)+'</dd><dt>Labor</dt><dd>'+money(j.estimate?.labor)+'</dd><dt>Other</dt><dd>'+money(j.estimate?.fees)+'</dd><dt>Total</dt><dd><strong>'+money(j.estimateTotal)+'</strong></dd><dt>Deposit</dt><dd>'+money(j.estimate?.deposit)+'</dd></dl></article></div>';
    body+='<article class="panel detail-section"><div class="panel-head"><h3>Requested scope</h3><span class="badge">'+(j.services||[]).length+' service'+((j.services||[]).length===1?'':'s')+'</span></div><p>'+esc(j.requestNotes||'')+'</p><div class="service-chips">'+(j.services||[]).map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></article>';
    body+=quoteBlock(j,c,v);
    if(['Awaiting Deposit','Scheduled','Awaiting Parts','Ready for Check-In','Checked In','Awaiting Final Authorization','In Progress','Waiting on Customer','Waiting on Parts','QC','Ready for Pickup','Delivered','Closed'].includes(j.status))body+=planningBlock(j);
    if(['Ready for Check-In','Checked In','Awaiting Final Authorization','In Progress','Waiting on Customer','Waiting on Parts','QC','Ready for Pickup','Delivered','Closed'].includes(j.status))body+=checkInBlock(j);
    if(['Awaiting Final Authorization','In Progress','Waiting on Customer','Waiting on Parts','QC','Ready for Pickup','Delivered','Closed'].includes(j.status))body+=authorizationBlock(j);
    if(j.workOrderId)body+=workOrderBlock(j);
    document.getElementById('jobDetailBody').innerHTML=body;
    document.getElementById('saveStatusBtn').onclick=()=>setStatus(document.getElementById('detailStatus').value);
    document.getElementById('nextActionBtn')?.addEventListener('click',()=>advance(j));
    document.getElementById('generateQuoteBtn')?.addEventListener('click',()=>generateQuote(j));
    document.getElementById('printQuoteBtn')?.addEventListener('click',()=>printQuote(j));
    document.getElementById('emailQuoteBtn')?.addEventListener('click',()=>emailQuote(j));
    document.getElementById('markSentBtn')?.addEventListener('click',()=>markSent(j));
    document.getElementById('approveQuoteBtn')?.addEventListener('click',()=>approveQuote(j));
    document.getElementById('declineQuoteBtn')?.addEventListener('click',()=>declineQuote(j));
    document.getElementById('clearApprovalPadBtn')?.addEventListener('click',clearApprovalPad);
    document.getElementById('savePlanBtn')?.addEventListener('click',()=>savePlan(j));
    document.getElementById('recordDepositBtn')?.addEventListener('click',()=>recordDeposit(j));
    const ci=document.getElementById('checkInForm');if(ci)ci.onsubmit=e=>saveCheckIn(e,j);
    const auth=document.getElementById('authorizeBtn');if(auth)auth.onclick=()=>authorizeWork(j);
    bindApprovalPad();
  };

  function nextButton(j){const m={Lead:'Generate Quote',Estimate:'Send / Print Quote','Awaiting Approval':'Awaiting Customer','Awaiting Deposit':'Record Deposit',Scheduled:'Ready for Check-In','Awaiting Parts':'Update Parts', 'Checked In':'Review Final Scope','In Progress':'Send to QC',QC:'Ready for Pickup','Ready for Pickup':'Mark Delivered',Delivered:'Close Job'};return m[j.status]?'<button class="btn primary" id="nextActionBtn" '+(j.status==='Awaiting Approval'?'disabled':'')+'>'+m[j.status]+'</button>':''}
  function advance(j){if(j.status==='Lead')return generateQuote(j);if(j.status==='Estimate')return document.getElementById('quoteActions')?.scrollIntoView({behavior:'smooth'});if(['Awaiting Deposit','Awaiting Parts'].includes(j.status))return document.getElementById('planningCard')?.scrollIntoView({behavior:'smooth'});const m={Scheduled:'Ready for Check-In','Checked In':'Awaiting Final Authorization','In Progress':'QC',QC:'Ready for Pickup','Ready for Pickup':'Delivered',Delivered:'Closed'};if(m[j.status])setStatus(m[j.status])}

  function generateQuote(j){if(j.quote?.approval){toast('This quotation is already approved. Use a change order for scope changes.');return}const now=new Date(),exp=new Date(now.getTime()+14*86400000);j.quote=j.quote||{id:newQuoteId(),version:0};j.quote.version=(j.quote.version||0)+1;j.quote.status='Draft';j.quote.generatedAt=now.toISOString();j.quote.expiresAt=exp.toISOString();j.quote.snapshot=snapshot(j);delete j.quote.sentAt;delete j.quote.approval;j.quoteId=j.quote.id;j.status='Estimate';touch(j,'quote_generated',{quoteId:j.quote.id,version:j.quote.version});render();toast(j.quote.id+' generated')}

  function quoteBlock(j,c,v){if(!j.quote)return '<article class="panel detail-section quote-card emphasis"><div class="panel-head"><div><p class="eyebrow">NEXT DOCUMENT</p><h3>Generate Quotation</h3><p class="muted">Freeze the reviewed job scope and draft pricing into a customer-facing quotation.</p></div><span class="badge">Not generated</span></div><div class="quote-actions"><button class="btn primary" id="generateQuoteBtn">Generate Quote</button><a class="btn secondary link-as-btn" target="_blank" rel="noopener" href="'+QUOTE_TEMPLATE_URL+'">View Drive Template</a></div></article>';
    const q=j.quote,s=q.snapshot||snapshot(j);let h='<article class="panel detail-section quote-card" id="quoteActions"><div class="panel-head"><div><p class="eyebrow">CUSTOMER QUOTATION</p><h3>'+esc(q.id)+' · Version '+esc(q.version)+'</h3><p class="muted">'+esc(q.status)+(q.sentAt?' · sent '+new Date(q.sentAt).toLocaleString():'')+'</p></div><span class="badge">'+esc(q.status)+'</span></div><div class="quote-summary-grid"><div><span>Customer</span><strong>'+esc(c.name||'')+'</strong></div><div><span>Vehicle</span><strong>'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</strong></div><div><span>Total</span><strong>'+money(s.estimateTotal)+'</strong></div><div><span>Deposit</span><strong>'+money(s.estimate?.deposit)+'</strong></div></div><div class="quote-actions"><button class="btn secondary" id="printQuoteBtn">Print / Save PDF</button><button class="btn secondary" id="emailQuoteBtn">Open Email Draft</button>';
    if(!q.approval)h+='<button class="btn primary" id="markSentBtn">Mark Sent / Presented</button>';h+='</div></article>';
    if(j.status==='Awaiting Approval'&&!q.approval)h+=approvalBlock(j,c);if(q.approval)h+=approvalRecord(q);return h}

  function markSent(j){j.quote.status='Sent';j.quote.sentAt=new Date().toISOString();j.status='Awaiting Approval';touch(j,'quote_sent',{quoteId:j.quote.id});render();toast('Quote is now awaiting customer approval')}
  function emailQuote(j){const c=customer(j.customerId)||{},v=vehicle(j.vehicleId)||{},q=j.quote;const subject='TTT Quotation '+q.id+' — '+[v.year,v.make,v.model].filter(Boolean).join(' ');const body='Hi '+(c.firstName||c.name||'')+',\n\nThank you for the opportunity to work on your '+[v.year,v.make,v.model].filter(Boolean).join(' ')+'.\n\nQuotation: '+q.id+'\nEstimated total: '+money(q.snapshot.estimateTotal)+'\nDeposit requested: '+money(q.snapshot.estimate?.deposit)+'\n\nPlease review the quotation. TTT will record approval before scheduling and beginning work.\n\nThompson Transportation Technologies';window.location.href='mailto:'+encodeURIComponent(c.email||'')+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);touch(j,'quote_email_draft_opened',{quoteId:q.id});toast('Email draft opened')}
  function printQuote(j){const c=customer(j.customerId)||{},v=vehicle(j.vehicleId)||{},q=j.quote,s=q.snapshot||snapshot(j);const rows=(s.equipment||[]).map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc([x.category,x.brand,x.model].filter(Boolean).join(' · '))+(x.note?'<br><small>'+esc(x.note)+'</small>':'')+'</td><td>'+esc(x.qty||1)+'</td></tr>').join('')||'<tr><td>1</td><td>'+esc((s.services||[]).join(', '))+'</td><td>1</td></tr>';const w=window.open('','_blank');if(!w){toast('Allow pop-ups to print');return}w.document.write('<!doctype html><html><head><title>'+esc(q.id)+'</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:38px}header{display:flex;justify-content:space-between;border-bottom:3px solid #1557c0;padding-bottom:18px}.brand{font-size:28px;font-weight:900}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:24px 0}.box{border:1px solid #dfe5ed;border-radius:10px;padding:16px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #e5e9ef;text-align:left}.totals{width:310px;margin-left:auto}.totals div{display:flex;justify-content:space-between;padding:6px}.total{border-top:2px solid #172033;font-size:18px;font-weight:800}</style></head><body><header><div><div class="brand">TTT</div><div>THOMPSON TRANSPORTATION TECHNOLOGIES</div></div><div><strong>QUOTATION / ESTIMATE</strong><br>'+esc(q.id)+' · Version '+esc(q.version)+'</div></header><div class="grid"><div class="box"><strong>Customer</strong><p>'+esc(c.name||'')+'<br>'+esc(c.phone||'')+'<br>'+esc(c.email||'')+'</p></div><div class="box"><strong>Vehicle</strong><p>'+esc([v.year,v.make,v.model,v.trim].filter(Boolean).join(' '))+'<br>VIN: '+esc(v.vin||'Not captured')+'</p></div></div><h3>Scope</h3><p>'+esc(s.requestNotes||'')+'</p><table><thead><tr><th>#</th><th>Service / Product</th><th>Qty</th></tr></thead><tbody>'+rows+'</tbody></table><div class="totals"><div><span>Parts</span><strong>'+money(s.estimate?.parts)+'</strong></div><div><span>Labor</span><strong>'+money(s.estimate?.labor)+'</strong></div><div><span>Other</span><strong>'+money(s.estimate?.fees)+'</strong></div><div class="total"><span>Total</span><strong>'+money(s.estimateTotal)+'</strong></div><div><span>Deposit</span><strong>'+money(s.estimate?.deposit)+'</strong></div></div><p style="margin-top:30px">Approval of this quotation is subject to vehicle check-in, final authorization and approved change orders.</p><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>');w.document.close();touch(j,'quote_printed',{quoteId:q.id})}

  function approvalBlock(j,c){return '<article class="panel detail-section approval-card emphasis"><div class="panel-head"><div><p class="eyebrow">CUSTOMER APPROVAL</p><h3>Approve Quotation</h3><p class="muted">Record the signer and capture a digital sign-off when approving in person.</p></div><span class="badge">Awaiting customer</span></div><div class="approval-grid"><label>Signer name<input id="quoteSignerName" value="'+esc(c.name||'')+'"></label><label>Signer email<input id="quoteSignerEmail" value="'+esc(c.email||'')+'"></label><label>Approval method<select id="quoteApprovalMethod"><option>In-person digital sign-off</option><option>Email confirmation</option><option>Printed signed copy</option></select></label></div><label class="consent"><input type="checkbox" id="quoteApprovalCheck"> Customer approves the quoted scope and price and understands final authorization occurs after vehicle check-in.</label><div class="approval-pad-wrap"><div class="approval-pad-head"><strong>Customer sign-off</strong><button class="link-btn" type="button" id="clearApprovalPadBtn">Clear</button></div><canvas id="quoteApprovalCanvas" width="900" height="230"></canvas><small>Use finger, stylus or mouse for in-person approval.</small></div><div class="approval-actions"><button class="btn primary" id="approveQuoteBtn">Approve Quote</button><button class="btn secondary" id="declineQuoteBtn">Decline Quote</button></div></article>'}
  function bindApprovalPad(){const c=document.getElementById('quoteApprovalCanvas');if(!c)return;const x=c.getContext('2d');x.lineWidth=2.2;x.lineCap='round';x.strokeStyle='#172033';let down=false;const p=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.dataset.hasInk='false';c.onpointerdown=e=>{down=true;c.setPointerCapture(e.pointerId);const q=p(e);x.beginPath();x.moveTo(q.x,q.y)};c.onpointermove=e=>{if(!down)return;const q=p(e);x.lineTo(q.x,q.y);x.stroke();c.dataset.hasInk='true'};c.onpointerup=c.onpointercancel=()=>down=false}
  function clearApprovalPad(){const c=document.getElementById('quoteApprovalCanvas');if(!c)return;c.getContext('2d').clearRect(0,0,c.width,c.height);c.dataset.hasInk='false'}
  function approveQuote(j){const ok=document.getElementById('quoteApprovalCheck')?.checked,name=document.getElementById('quoteSignerName')?.value.trim(),email=document.getElementById('quoteSignerEmail')?.value.trim(),method=document.getElementById('quoteApprovalMethod')?.value,c=document.getElementById('quoteApprovalCanvas');if(!ok||!name){toast('Customer acknowledgement and signer name are required');return}if(method==='In-person digital sign-off'&&c?.dataset.hasInk!=='true'){toast('Please capture the customer sign-off');return}const now=new Date().toISOString();j.quote.approval={id:newApprovalId(),status:'Approved',method,signerName:name,signerEmail:email,approvedAt:now,termsVersion:'0.3',approvalMark:c?.dataset.hasInk==='true'?c.toDataURL('image/png'):null};j.quote.status='Approved';const depReady=(+j.depositReceived||0)>=(+j.estimate?.deposit||0),partsReady=['Parts received','No special parts required','Customer supplied'].includes(j.partsStatus);j.status=!depReady?'Awaiting Deposit':(!partsReady?'Awaiting Parts':'Scheduled');touch(j,'quote_approved',{quoteId:j.quote.id,approvalId:j.quote.approval.id});render();toast('Quote approved')}
  function declineQuote(j){if(!confirm('Mark this quotation as declined?'))return;j.quote.status='Declined';j.status='Declined';touch(j,'quote_declined',{quoteId:j.quote.id});render();toast('Quote declined')}
  function approvalRecord(q){const a=q.approval||{};return '<article class="panel detail-section approval-record"><div class="panel-head"><div><h3>Quote Approval</h3><p class="muted">Locked approval record for '+esc(q.id)+'</p></div><span class="badge">Approved</span></div><dl class="detail-list two-col"><dt>Approval ID</dt><dd>'+esc(a.id||'—')+'</dd><dt>Approved</dt><dd>'+esc(a.approvedAt?new Date(a.approvedAt).toLocaleString():'—')+'</dd><dt>Signer</dt><dd>'+esc(a.signerName||'—')+'</dd><dt>Method</dt><dd>'+esc(a.method||'—')+'</dd></dl>'+(a.approvalMark?'<img class="approval-mark-record" src="'+a.approvalMark+'" alt="Customer sign-off">':'')+'</article>'}

  function planningBlock(j){const dep=+j.estimate?.deposit||0,got=+j.depositReceived||0;return '<article class="panel detail-section" id="planningCard"><div class="panel-head"><div><p class="eyebrow">PRE-VISIT CONTROL</p><h3>Deposit, Parts & Scheduling</h3><p class="muted">Make sure the job is commercially and operationally ready before check-in.</p></div><span class="badge">'+esc(displayStatus(j.status))+'</span></div><div class="fulfillment-grid"><div class="mini-stat"><span>Deposit required</span><strong>'+money(dep)+'</strong><small>Received: '+money(got)+'</small></div><label>Parts status<select id="planPartsStatus"><option '+(j.partsStatus==='No special parts required'?'selected':'')+'>No special parts required</option><option '+(j.partsStatus==='Need to confirm parts'?'selected':'')+'>Need to confirm parts</option><option '+(j.partsStatus==='Parts need ordering'?'selected':'')+'>Parts need ordering</option><option '+(j.partsStatus==='Parts ordered'?'selected':'')+'>Parts ordered</option><option '+(j.partsStatus==='Parts received'?'selected':'')+'>Parts received</option><option '+(j.partsStatus==='Customer supplied'?'selected':'')+'>Customer supplied</option></select></label><label>Appointment<input type="datetime-local" id="planAppointment" value="'+esc(j.appointment||'')+'"></label></div><div class="quote-actions">'+(dep>got?'<button class="btn secondary" id="recordDepositBtn">Record Deposit</button>':'')+'<button class="btn primary" id="savePlanBtn">Save Plan</button></div></article>'}
  function recordDeposit(j){const need=Math.max((+j.estimate?.deposit||0)-(+j.depositReceived||0),0),v=prompt('Deposit amount received',String(need));if(v===null)return;const n=+v;if(!Number.isFinite(n)||n<0){toast('Enter a valid amount');return}j.depositReceived=(+j.depositReceived||0)+n;touch(j,'deposit_recorded',{amount:n});render();toast('Deposit recorded')}
  function savePlan(j){j.partsStatus=document.getElementById('planPartsStatus')?.value||j.partsStatus;j.appointment=document.getElementById('planAppointment')?.value||j.appointment;const depReady=(+j.depositReceived||0)>=(+j.estimate?.deposit||0),partsReady=['No special parts required','Parts received','Customer supplied'].includes(j.partsStatus);j.status=!depReady?'Awaiting Deposit':(!partsReady?'Awaiting Parts':'Scheduled');touch(j,'previsit_plan_updated',{partsStatus:j.partsStatus,appointment:j.appointment});render();toast('Plan updated')}

  authorizeWork=function(j){const check=document.getElementById('finalAuthCheck'),name=document.getElementById('finalAuthName');if(!check?.checked||!name?.value.trim()){toast('Customer authorization is required');return}const now=new Date().toISOString();j.finalAuthorization={id:newApprovalId(),name:name.value.trim(),at:now,termsVersion:'0.3'};j.workOrderId=newWorkOrderId();j.status='In Progress';touch(j,'final_authorization_and_work_order_created',{workOrderId:j.workOrderId,approvalId:j.finalAuthorization.id});render();toast(j.workOrderId+' created')};

  prepNewJob();render();
})();
