const assert=require('assert');
const Core=require('../scheduling-core-v09.js');
function db(){return {jobs:[],customers:[],vehicles:[]};}
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
test('adds scheduling model without replacing existing data',()=>{const d=db();d.keep='yes';Core.ensureModel(d);assert.equal(d.keep,'yes');assert.ok(d.scheduling.serviceTemplates.length>=10);});
test('diagnostic defaults to 15 minutes',()=>{const d=db();assert.equal(Core.getTemplate(d,'Diagnostic').defaultMinutes,15);});
test('window tint defaults to four hours',()=>{const d=db();assert.equal(Core.getTemplate(d,'Window tint').defaultMinutes,240);});
test('model initialization is idempotent',()=>{const d=db();Core.ensureModel(d);const n=d.scheduling.serviceTemplates.length;Core.ensureModel(d);assert.equal(d.scheduling.serviceTemplates.length,n);});
test('generates job operation tied to job',()=>{const d=db();const j={id:'J1',services:['Window tint'],appointment:'2026-09-15T09:00',workOrderId:null};d.jobs=[j];const ops=Core.generateJobOperations(d,j);assert.equal(ops.length,1);assert.equal(ops[0].jobId,'J1');assert.equal(ops[0].durationMinutes,240);assert.ok(ops[0].resourceId);});
test('detects technician conflict',()=>{const d=db();Core.ensureModel(d);d.scheduling.operations=[{id:'a',jobId:'1',service:'Diagnostic',start:'2026-09-15T09:00',durationMinutes:60,bufferMinutes:0,technicianId:'tech_derek',resourceId:'res_diag_1',status:'scheduled'}];const c={id:'b',jobId:'2',service:'Other',start:'2026-09-15T09:30',durationMinutes:30,bufferMinutes:0,technicianId:'tech_derek',resourceId:'res_install_1',status:'scheduled'};assert.ok(Core.operationConflicts(d,c).some(x=>x.type==='technician'));});
test('detects bay conflict',()=>{const d=db();Core.ensureModel(d);d.scheduling.operations=[{id:'a',jobId:'1',service:'Window tint',start:'2026-09-15T09:00',durationMinutes:240,bufferMinutes:15,technicianId:'tech_derek',resourceId:'res_tint_1',status:'scheduled'}];const c={id:'b',jobId:'2',service:'Window tint',start:'2026-09-15T12:00',durationMinutes:60,bufferMinutes:0,technicianId:'',resourceId:'res_tint_1',status:'scheduled'};assert.ok(Core.operationConflicts(d,c).some(x=>x.type==='resource'));});
test('next start moves after occupied slot',()=>{const d=db();Core.ensureModel(d);d.scheduling.operations=[{id:'a',jobId:'1',service:'Diagnostic',start:'2026-09-15T08:00',durationMinutes:60,bufferMinutes:0,technicianId:'tech_derek',resourceId:'res_diag_1',status:'scheduled'}];const t=Core.suggestNextStart(d,{from:'2026-09-15T08:00',durationMinutes:15,technicianId:'tech_derek',resourceId:'res_diag_1'});assert.ok(t>=new Date('2026-09-15T09:00'));});
test('status tracks actual time',()=>{const d=db();Core.ensureModel(d);const op=Core.upsertOperation(d,{id:'x',start:'2026-09-15T09:00',durationMinutes:60});Core.setOperationStatus(d,'x','in_progress','2026-09-15T09:05:00');Core.setOperationStatus(d,'x','complete','2026-09-15T10:20:00');assert.equal(Core.actualMinutes(op),75);assert.equal(Core.variance(op).difference,15);});
test('capacity summary counts scheduled minutes',()=>{const d=db();Core.ensureModel(d);d.scheduling.operations=[{id:'x',start:'2026-09-15T09:00',durationMinutes:240,bufferMinutes:0,status:'scheduled'}];const x=Core.capacitySummary(d,'2026-09-15T12:00');assert.equal(x.scheduledMinutes,240);assert.equal(x.operationCount,1);});
if(!process.exitCode)console.log(`\n${passed} scheduling tests passed.`);